export const SET_CORRECT_ANSWER_NUMBER = 'SET_CORRECT_ANSWER_NUMBER';
export const PROCEED_TO_NEXT_STAGE = 'PROCEED_TO_NEXT_STAGE';

export const HANDLE_CORRECT_ANSWER = 'HANDLE_CORRECT_ANSWER';
export const HANDLE_INCORRECT_ANSWER = 'HANDLE_INCORRECT_ANSWER';
