export const SET_CORRECT_ANSWER_ID = 'SET_CORRECT_ANSWER_ID';
export const PROCEED_TO_NEXT_STAGE = 'PROCEED_TO_NEXT_STAGE';

export const HANDLE_CORRECT_ANSWER = 'HANDLE_CORRECT_ANSWER';
export const HANDLE_INCORRECT_ANSWER = 'HANDLE_INCORRECT_ANSWER';

export const RESTART_GAME = 'RESTART_GAME';

export const SET_PLAYING_COMPONENT = 'SET_PLAYING_COMPONENT';
export const RESET_PLAYING_COMPONENT = 'RESET_PLAYING_COMPONENT';
